version: '3.9'

services:
  db:
    image: postgres:16
    container_name: attendance-qr-db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: attendance-qr-redis
    ports:
      - "6379:6379"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-qr-web
    env_file: .env
    environment:
      - RUNNING_MODE=web
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: ["./entrypoint.sh"]
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-qr-worker
    env_file: .env
    environment:
      - RUNNING_MODE=worker
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=attendance.settings
    depends_on:
      - web
      - redis
    command: ["celery", "-A", "attendance", "worker", "-l", "info"]
    restart: always

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-qr-beat
    env_file: .env
    environment:
      - RUNNING_MODE=beat
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - web
      - redis
    command: ["celery", "-A", "attendance", "beat", "-l", "info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    restart: always

volumes:
  db_data:
