# Generated by Django 5.2.5 on 2025-09-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='08:00:00', verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(default='17:00:00', verbose_name='ساعت پایان')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='مدت تاخیر(دقیقه)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('late', 'دیرکرد')], default='absent', max_length=10, verbose_name='وضعیت'),
        ),
    ]
