# Generated by Django 5.2.5 on 2025-08-30 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='آی دی کاربر')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes', verbose_name='بارکد اختصاصی')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('check_in_time', models.TimeField(auto_now_add=True, verbose_name='ساعت')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('late', 'دیرکرد')], default='present', max_length=10, verbose_name='وضعیت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee', verbose_name='کاربر')),
            ],
        ),
    ]
