# Generated by Django 5.2.5 on 2025-09-05 22:59

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workschedule_attendance_late_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
    ]
